# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build -x test'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'

- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '$(Agent.BuildDirectory)/build/libs'
    Contents: '*.jar'
    ArtifactName: 'app.jar'
    ArtifactType: 'FilePath'