# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  image-name: humberd/notes-app-server
  amd64-tag: amd64-$(Build.BuildId)
  armv7-tag: amd64-$(Build.BuildId)
  manifest-tag: $(build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: 'DockerHub - Humberd'

  - task: Docker@2
    displayName: Build linux/amd64
    inputs:
      repository: $(image-name)
      command: 'build'
      Dockerfile: 'docker/amd64.Dockerfile'
      buildContext:
      tags: $(amd64-tag)
      addPipelineData: false

  - task: Docker@2
    displayName: Build linux/arm/v7
    inputs:
      repository: $(image-name)
      command: 'build'
      Dockerfile: 'docker/armv7.Dockerfile'
      buildContext:
      tags: $(armv7-tag)
      addPipelineData: false

  - task: Docker@2
    displayName: Push linux/amd64
    inputs:
      containerRegistry: 'DockerHub - Humberd'
      repository: $(image-name)
      command: 'push'
      tags: $(amd64-tag)

  - task: Docker@2
    displayName: Push linud/arm/v7
    inputs:
      containerRegistry: 'DockerHub - Humberd'
      repository: $(image-name)
      command: 'push'
      tags: $(armv7-tag)

  - task: Bash@3
    displayName: Build and Push Manifest
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        docker manifest create $(image-name):latest /
                $(image-name):$(amd64-tag) /
                $(image-name):$(armv7-tag)

        docker manifest create $(image-name):$(manifest-tag) /
                $(image-name):$(amd64-tag) /
                $(image-name):$(armv7-tag)

        docker manifest push $(image-name):latest
        docker manifest push $(image-name):$(manifest-tag)

  - task: Docker@2
    displayName: Logout
    condition: always()
    inputs:
      command: logout
      containerRegistry: 'DockerHub - Humberd'
